### ISSUE TITLE
misclassified pictures anschauen 

### ISSUE THREAD

**Issue by KiliTili** [SarahDbnr/adl_SteinVI#1]

**Comment by KiliTili** [comment]
War die Idee von Luke, einfach dass wir bei MNIST z.B. anschauen welche Bilder nicht passen.

**Comment by KiliTili** [comment]
Bereit zum review

**Comment by LukeBer** [comment]
currently not working with class labels, shouldn't be the missclassified value be at the spot where the Class votes from particles: [0 0 0 0 3 0 0 6 1 0] has the most votes. this is not the case. further it would be interesting to see the probability prior to the argmax argument. and maybe we dont need to. see every misclassified case. maybe just a random sample of 5 or something @KiliTili
