### ISSUE TITLE
TODO: @KiliTili "Musste dies auskommentieren für MNIST"

### ISSUE THREAD

**Issue by SarahDbnr** [SarahDbnr/adl_SteinVI#14]
in BNN_Model

**Comment by KiliTili** [comment]
hier war ich einfach nicht sicher, ob dies algemein gebraucht wird ich glaube nämlich nicht, ich hatte aber den ursprünglichen code nicht geschrieben, deshalb war ich mir unsicher, ich glaube der originale code war von @LukeBer
