### ISSUE TITLE
TODO: Rethink order of calculating accuracy

### ISSUE THREAD

**Issue by SarahDbnr** [SarahDbnr/adl_SteinVI#15]
In validation_and_evaluation

1. precisions, mean, argmax
2. or precisions, argmax, mean

not in prediction function argmax(precisions)=prediction, so if second option is chosen just use mean(predictions) not mean(argmax(precsions))

**Comment by KiliTili** [comment]
@LukeBer passt dass nun so

**Comment by KiliTili** [comment]
@LukeBer @SarahDbnr  hier ergibt es wahrscheinlich sinn nach 2. zu gehen, da wir bei zuerst mean eigentlich nicht die einzelnen Partikel betrachten sollten wir heute mit ihm absprechen
