### ISSUE TITLE
Random shuffle for minibatches and maybe jitten der loop

### ISSUE THREAD

**Issue by KiliTili** [SarahDbnr/adl_SteinVI#16]
Problem ist, dass wenn wir die daten in jeder Iteration mischen und aufteilen wir extrem lange warten müssen, zumindest, wenn wir vor direkt vor if batch_size != "Full":
print("Batching") machen.
Im moment haben wir nicht wirklich Minibatching, da wir in jeder iteration einfach nur die gleichen Batches nehmen und dieses in den Algorithmus hineingeben, damit wir mit der Datenmenge umgehen können
hier müsste man schauen wie es schneller geht Überlegung war über jitten, deshalb hatte ichs glaube ich mal Luke zugewiesen im alten repo

**Comment by LukeBer** [comment]
Fange damit an.

**Comment by LukeBer** [comment]
Done and merged branch with main. Commit 900675b
