### ISSUE TITLE
Residual plots for regression

### ISSUE THREAD

**Issue by KiliTili** [SarahDbnr/adl_SteinVI#24]
-also with precision in relation to mu

**Comment by KiliTili** [comment]
@SarahDbnr Soll ich dort einen Branche vom Mainbranch nehmen oder sind die regressionsergebnisse woanders?

**Comment by KiliTili** [comment]
Ich hatte jetzt eine Plot erstellt, der die Scale in Relationship zum Location Plottert, wenn @LukeBer oder @SarahDbnr  kurz r+berscheinen könntet wäre es super, also die Funktion läuft durch und ist im main, könnt ja einfach euch das Issue aussingen  und closen

**Comment by LukeBer** [comment]
ich persönlich verstehe nicht so richtig, was uns dieser plot zeigen soll

**Comment by KiliTili** [comment]
@LukeBer  fixes für neue CIs
