### ISSUE TITLE
TODO: Verschiedene Link Funktionen für Varianzfunktion

### ISSUE THREAD

**Issue by KiliTili** [SarahDbnr/adl_SteinVI#3]
- exp()
- ln()
- abs()
- ohne

**Comment by SarahDbnr** [comment]
1) das ist ein immer wieder auftretendes Phänomen, dass die Varianz explodiert. Folgende Dinge können helfen, aber nicht alles klappt immer: 
a) am einfachsten: clipping. Ihr macht quasi einfach jnp.clip um den exp herum auf einen "akzeptablen Wert" welcher aber nicht zu niedrig sein sollte. 
b) anstelle von exp nehmt ihr als Link log(1+exp(X)). Dann ist die gelernte funktionale Form linear in X und nicht exponentiell. Man kann auch noch einen Faktor < 1 vor X setzen. 
c) Prioris anpassen: alle Gewichte in der letzten layer, die für Sigma benutzt werden mit einer priori versehen, die zb ~N(0,s) mit s<1. Das muss in Abhängigkeit von der davor sitzenden activation function aber ggf nicht funktionieren.
