### ISSUE TITLE
Regression mit einem Output neuron

### ISSUE THREAD

**Issue by KiliTili** [SarahDbnr/adl_SteinVI#31]
@LukeBer  and @SarahDbnr ich hatte gerade mit Luke geschrieben, ob wir auch regression mit einem output Neuron aufnehmen sollen, also ohne Varianz, der aktuelle Code funktioniert dafür nicht, sollten wir aber vielleicht mit ihm absprechen

**Comment by SarahDbnr** [comment]
Warum wollt ihr einen Output haben, passt das dann noch zu basian neural networks?

**Comment by LukeBer** [comment]
brauchen wir nicht, können wir aber adden, wenn wir nur mean zb schätzen wollen. kilian meinte, dass wir bei regression die outputsize ansonsten fest setzen können. ich würde das einfach erstmal alles so lassen und wenn wir wann brauchen sollten erneut angehen
