### ISSUE TITLE
add else in create_particle_minibatch_indices

### ISSUE THREAD

**Issue by SarahDbnr** [SarahDbnr/adl_SteinVI#40]
def create_particle_minibatch_indices(key, num_particles, batch_size):
    if num_particles < batch_size:
        num_batches = 2 # Unsued
        print("\n WARNING: Batch size to large, particle batching with 2 batches will be used!")
    indices = jax.random.permutation(key, num_particles)
    num_batches = max(1, num_particles // batch_size)
    batched_indices = jnp.array_split(indices, num_batches)
    return batched_indices

**Comment by KiliTili** [comment]
Sollte gefixed sein, kannst ja nochmal im main über die Funktion schauen
