### ISSUE TITLE
barplot with errorplots geomerrorbar plot9

### ISSUE THREAD

**Issue by KiliTili** [SarahDbnr/adl_SteinVI#56]

**Comment by KiliTili** [comment]
use 94 %  band to be arbitrary

**Comment by KiliTili** [comment]
Is included, but not sure if we should use mean to compute the error bars

**Comment by LukeBer** [comment]
kann beides machen, mean when assumption of normality is met, median is not. both possible no right / wrong. would leave it the way its computed @KiliTili
