### ISSUE TITLE
Fix particle minibatching for quasi SVN

### ISSUE THREAD

**Issue by KiliTili** [SarahDbnr/adl_SteinVI#63]
Hi @LukeBer,  ich bin nicht genug in der Struktur für das Partikel minibatching drin, wenn du dir dass bei zeit anschauen könntest wäre es super, sonst ist es auch nicht schlimm, dann würde ich einfach eine Warnung machen, dass minibatching für particle nicht möglich ist für quasi svn. 

Dass sollte eins der letzten Sachen sein die wir uns anschauen, da es ja nur ein bonus ist, also Doku und Tests haben Vorrang:)

**Comment by LukeBer** [comment]
machen wir beim fixen des algorithm codes
